language: java
jdk:
  - oraclejdk8

services:
  - docker

script:
  - mvn package

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASS
  - export REPO=awmh/hackday
  - export TAG=latest
  - docker build -f Dockerfile -t $REPO:$COMMIT
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO