language: java
jdk:
  - oraclejdk8

services:
  - docker

script:
  - mvn package

after_success:
  - docker login -u awmh -p ${DOCKER_PASS}
  - export REPO=awmh/hackday
  - export TAG=latest
  - docker build -t $REPO .
  - docker tag $REPO $REPO:$TAG
  - docker tag $REPO $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO