sudo: required
language: java
jdk:
  - oraclejdk8

services:
  - docker

script:
  - mvn package

after_success:
  - pip install --user awscli'
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region eu-west-1)
  - docker build -t hackday .
  - docker tag hackday:latest 034510918061.dkr.ecr.eu-west-1.amazonaws.com/hackday:latest
  - docker push 034510918061.dkr.ecr.eu-west-1.amazonaws.com/hackday:latest